### ISSUE TITLE
Extension Signing

### ISSUE THREAD

**Issue by julianrichen** [IsSuEat/open-livestreamer-firefox-addon#41]
As of Firefox 43 all extensions should be signed and as of Firefox 44 must be signed. Addons/Extensions can not be run without them, not even an option exists to disable the requirement (in Firefox 44). I'm not sure if you have signed the addon yet but a self-sign can be done with `jpm`:

``` bash
jpm sign --api-key ${AMO_API_KEY} --api-secret ${AMO_API_SECRET}
```

[Source](https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm#jpm_sign) & [Singing Info](https://wiki.mozilla.org/Add-ons/Extension_Signing)

**Comment by IsSuEat** [comment]
This is currently not working for me. 
```
Successfully created xpi at /home/issue/projects/open-livestreamer-firefox-addon/jid1-Y6BhyMM8GoZ3eA@jetpack-2.0.1.xpi
Validating add-on [ .. ...... .  ..... ... .. ...  ..  ..... .   ...   ....  .  .....   .... .. .... . . . .. .... .. ....    . . ... ... ..    .   .  . .. ... ....... ]Potentially unhandled rejection [1] Error: Received bad response from the server; status: 500; response: <?xml version="1.0" encoding="utf-8" ?>
      <error>Server Error</error>
  
    at /usr/lib/node_modules/jpm/lib/amo-client.js:397:15
    at tryCatchReject (/usr/lib/node_modules/jpm/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/usr/lib/node_modules/jpm/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/usr/lib/node_modules/jpm/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/usr/lib/node_modules/jpm/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/usr/lib/node_modules/jpm/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/usr/lib/node_modules/jpm/node_modules/when/lib/Scheduler.js:27:9)
    at doNTCallback0 (node.js:430:9)
    at process._tickCallback (node.js:359:13)
Validating add-on [.....................................................................................................................................................]FAIL
Error: Validation took too long to complete; last status: {"active":true,"url":"https://addons.mozilla.org/api/v3/addons/jid1-Y6BhyMM8GoZ3eA%40jetpack/versions/2.0.1/","files":[],"passed_review":true,"processed":true,"reviewed":true,"valid":true,"validation_results":{"errors":0,"success":false,"warnings":4,"compatibility_summary":{"notices":0,"errors":0,"warnings":0},"passed_auto_validation":true,"ending_tier":5,"messages":[{"file":"bootstrap.js","editors_only":false,"description":"Access to the `Components` property is deprecated for security or other...
    at null._onTimeout (/usr/lib/node_modules/jpm/lib/amo-client.js:150:14)
    at Timer.listOnTimeout (timers.js:92:15)
```
I will try later again

**Comment by julianrichen** [comment]
I'm not sure if you managed to get it signed but I found a new blog post:
https://blog.mozilla.org/addons/2015/11/20/signing-api-now-available/

Maybe the cURL method is easier?

**Comment by julianrichen** [comment]
Was this fixed? The addon still seems to work after FF43 landed so I guess you got signing done?
